# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb9dbaed47fcf299f8121f0dc6d109c2a0ae71c0142e6a0874cb1737a58cd1490c1a12565e34467e8e0685c83dce9d9dfd70640b873d7b341884fa50769e625a

test:
  secret_key_base: f5c4d999ad73d3a8d7629a1a671d1192126a90249fbd7bd96a2f2faeec54138885c7bf7f1dce3d39f8ec3eca8c80aa5b6bd529202d39a6bdd673e21bf09ee97b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
